Error out when no valid ipv4 addresses have been resolved

diff --git a/scripts/unblock b/scripts/unblock
--- a/scripts/unblock
+++ b/scripts/unblock
@@ -45,17 +45,17 @@ done
 
 readarray -t resolved < <( dig -4 +short "${domains[@]}" | uniq )
 
-if [[ "${#resolved[@]}" -eq 0 ]]; then
-  printf '%s\n' "Couldn't resolve ips." > "${erroutput}" 
-  exit 1
-fi
-
 # Filter out ipv6
 for ip in "${resolved[@]}"; do
   if [[ "${ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
     ips+=( "${ip}" )
   fi
 done
+
+if [[ "${#ips[@]}" -eq 0 ]]; then
+  printf '%s\n' "Couldn't resolve ips." > "${erroutput}" 
+  exit 1
+fi
 
 for ip in "${ips[@]}"; do
   if [[ "${erase}" == 'true' ]]; then
